name: Test detekt - old 

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Test Action

    strategy:
      max-parallel: 6
      fail-fast: true
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-latest
          - macos-latest
        detekt_version:
          - 1.15.0
          - 1.14.2
          - v1.13.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Run Action
        id: get_detekt
        uses: ./
        with:
          detekt_version: ${{ matrix.detekt_version }}

      - name: Report location of tool
        run: |
          echo "detekt ${{ steps.get_detekt.outputs.detekt }}"

      - name: Run detekt
        run: |
          detekt --version