name: Test detekt 

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Test Action

    strategy:
      max-parallel: 8
      fail-fast: true
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - windows-latest
          - macos-latest
        detekt_version:
          - '1.18'
          - '1.20'
          - ''

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Run Action
        id: get_detekt
        uses: ./
        with:
          detekt_version: ${{ matrix.detekt_version }}

      - name: Report location of tool
        run: |
          echo "detekt ${{ steps.get_detekt.outputs.detekt }}"

      - name: Run detekt CLI
        run: |
          detekt-cli --version
